# Site settings
title: Sekadar Awan
#email:
description: > # this means to ignore newlines until "baseurl:"
  Cuma blog-blogan, jangan terlalu serius
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sekadarawan.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  sekadarawan

# Build settings
markdown: kramdown

highlighter: pygments
